Repository StrawberryPick/Strawberry, pull requests merged in 2021-11, with the labels that each got.

#38 Update google map scraper script
  .gitignore
  code/__init__.py
  code/data/__init__.py
  code/data/collectingFarms.py
  code/data/scraper.py
Labels: enhancement, Scrum Two

#55 Add files via upload
  scrum/6PhasesS1.uxf
  scrum/DataInfrastructureFlow.drawio
  scrum/DataInfrastructureFlow.drawio.png
  scrum/TaskListS1
Labels: documentation

#75 Implementing Clustering and optimize scraper script
  .gitignore
  code/analysis/analysis.py
  code/analysis/transform.py
  code/analysis/visualization.py
  code/data/csv/England.csv
  code/data/scraper.py
Labels: Scrum Two

#122 create monthly review analysis
  code/analysis/transform.py
  code/data/csv/full_review_last_year.csv
  code/data/generateLastYearCsv.py
  code/graph/review_amount_monthly.png
  code/graph/review_amount_monthly_script.py
Labels: Scrum Two

#131 Update scrumOneDailyJournal.md
  scrum/scrumOneDailyJournal.md
Labels: Scrum One
